# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
